version: '3'

services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: LightDigital
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
